#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 12:59:10 2019

@author: schollpp
"""

import numpy as np

l = 5
data = np.genfromtxt("bananas-1-2d.test.csv", delimiter = ",")
x = np.array([0.25,0.25])
k = 5
n = np.size(data[1,:])


def d(x,b):
    n = np.size(x)
    s = 0
    for i in range(n):
        s = s + (x[i] - b[i+1])**2
    return s

def Abstand(D,k,x):
    values = []
    for i in range(k):
        a = d(x,D[i,:])
        values.append((a,i))
    dtype = [("Abstand" , float), ("Zeile", int)]
    Abstand = np.array(values, dtype=dtype)
    Abstand = np.sort(Abstand, order = "Abstand")
    for i in np.arange(k-1,np.size(D, axis = 0),1):
        a = d(x,D[i,:])
        for j in range(k):
            if a < Abstand[j][0]:
                for m in np.arange(k-1,j,-1):
                    Abstand[m] = Abstand[m-1]
                Abstand[j] = (a,i)
                break
    return Abstand

def f_Dk(D,k,x):
    Ab = Abstand(D,k,x)
    s = 0
    for i in range(k):
        s = data[Ab[i][1],0] + s
    
    if s == 0:
        f_Dk = 1
    else:
        f_Dk = np.sign(s)
    
    return f_Dk

b=np.size(data, axis = 0)
K=np.arange(10,21,1)
m=b % l
a=0
D=[]
for i in range(m):
    D.append(data[a:a+b/l+1,0:3])
    a=a+b/l+1
for i in range(l-m):
    D.append(data[a:a+b/l,0:3])
a=a+b/l

i=4
Di=np.zeros((b-np.size(D[i],axis=0),3))
a=0
for j in range(l):
    if (not j == i):
        Di[a:a+np.size(D[j],axis=0),0:3]=D[j]
        a=a+np.size(D[j],axis=0)
    else:
        Dj=D[j]
KDi=Abstand(Di,k,x)
f = 0
for j in range(np.size(D[i], axis = 0)):
    s = np.sign(f_Dk(Di,k,D[i][j,1:2]))
    if (not s == D[i][j,0]):
        f = f + 1 




print s
print f_Dk
    
print Ab
