#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 12:59:10 2019

@author: schollpp
"""

import numpy as np
import time

tic=time.time()

l = 5
data = np.genfromtxt("bananas-1-2d.test.csv", delimiter = ",")
x = np.array([0.5,0.5])
k = 10
n = np.size(data[1,:])


def no(x,b):
    n = np.size(x)
    s = 0
    for i in range(n):
        s = s + (x[i] - b[i+1])**2
    return s

def Abstand(D,k,x):
    values = []
    for i in range(k):
        a = no(x,D[i,:])
        values.append((a,i))
    dtype = [("Abstand" , float), ("Zeile", int)]
    Abstand = np.array(values, dtype=dtype)
    Abstand = np.sort(Abstand, order = "Abstand")
    for i in np.arange(k-1,np.size(D, axis = 0),1):
        a = no(x,D[i,:])
        if a < Abstand[k-1][0]:
            for j in range(k):
                if a < Abstand[j][0]:
                    for m in np.arange(k-1,j,-1):
                        Abstand[m] = Abstand[m-1]
                    Abstand[j] = (a,i)
                    break

    return Abstand
    

def f_Dk(D,k,x):
    Ab = Abstand(D,k,x)
    s = 0
    for z in range(k):
        s += D[Ab[z][1],0]
    
    if s == 0:
        f_Df = 1
    else:
        f_Df = np.sign(s)
    
    return f_Df

b=np.size(data, axis = 0)
K=np.arange(10,21,1)
m=b % l
a=0
D=[]
for i in range(m):
    D.append(data[a:a+b/l+1,0:3])
    a=a+b/l+1
for i in range(l-m):
    D.append(data[a:a+b/l,0:3])
    a=a+b/l

i=3
Di=np.zeros((b-np.size(D[i],axis=0),3))
a=0
for j in range(l):
    if (not j == i):
        Di[a:a+np.size(D[j],axis=0),0:3]=D[j]
        a=a+np.size(D[j],axis=0)
KDi=Abstand(Di,k,x)
f = 0
false=[]
for j in range(np.size(D[i], axis = 0)):
    s = f_Dk(Di,k,D[i][j,1:3])
    if(j==305):
        Ab = Abstand(Di,k,D[i][j,1:3])
        for z in range(k):
            print Ab[z]
    #print(s)
    if (not s == D[i][j,0]):
        f = f + 1
        false.append(j)
