#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 18 12:26:53 2019

@author: schollpp
"""
import numpy as np
import matplotlib.pyplot as plt

#Wir wollen jetzt plotten, diggi
name = "bananas-1-2d"
data2 = np.genfromtxt("{}.train.csv".format(name), delimiter = ",")

a=np.array([[0,0]])
b=np.array([[0,0]])
for i in range(np.size(data2,axis=0)):
    if(data2[i,0]<0):
        a=np.append(a,[data2[i,1:].tolist()],axis=0)
    else:
        b=np.append(b,[data2[i,1:].tolist()],axis=0)

plt.figure(figsize=(12, 12))
plt.scatter(a[1:,0],a[1:,1],s=0.5,color='red')
plt.scatter(b[1:,0],b[1:,1],s=0.5,color='blue')
